# Generated by Django 4.1.5 on 2023-01-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary_from', models.FloatField(verbose_name='Нижняя граница зарплаты')),
                ('salary_to', models.FloatField(verbose_name='Верхняя граница зарплаты')),
                ('area_name', models.CharField(max_length=100, verbose_name='Город')),
                ('published_at', models.DateTimeField(verbose_name='Время публикации')),
            ],
        ),
    ]
